import { Component,inject,signal } from '@angular/core';import { DatePipe,DecimalPipe } from '@angular/common';import { ApiService } from '@shared/api.service';import { ReportSummary,TradeActivity } from '@shared/models';import { SimpleChartComponent,ChartDatum } from '@shared/simple-chart.component';
@Component({selector:'app-warehouse-activity',standalone:true,imports:[DatePipe,DecimalPipe,SimpleChartComponent],template:`
<section class="page-heading"><div><p class="eyebrow">Data warehouse</p><h1>DW Activity</h1><p class="muted">ETL freshness, loaded executions and warehouse activity.</p></div><button (click)="load()">Refresh</button></section>
@if(summary();as s){<section class="metric-grid"><article><span>Warehouse rows</span><strong>{{s.trade_count}}</strong><small>Loaded executions</small></article><article><span>Latest load</span><strong class="metric-date">{{s.warehouse_last_loaded_at|date:'shortTime'}}</strong><small>{{s.warehouse_last_loaded_at|date:'mediumDate'}}</small></article><article><span>Instruments</span><strong>{{s.instruments_traded}}</strong><small>Distinct traded symbols</small></article><article><span>Active clients</span><strong>{{s.active_clients}}</strong><small>Clients represented in DW</small></article></section>}
<section class="dashboard-charts"><app-simple-chart title="Loads by day" subtitle="Warehouse rows grouped by load date" type="line" [data]="loadsByDay()"/><app-simple-chart title="Trades by symbol" subtitle="Loaded warehouse executions by ticker" [data]="tradesBySymbol()"/></section>
<section class="data-card"><div class="card-heading"><h2>Recently loaded trades</h2><p>Newest warehouse rows ordered by ETL load time.</p></div><table><thead><tr><th>Loaded</th><th>Filled</th><th>Order</th><th>Symbol</th><th>Side</th><th class="numeric">Quantity</th><th class="numeric">Notional</th></tr></thead><tbody>@for(r of recent();track r.order_id){<tr><td>{{r.loaded_at|date:'medium'}}</td><td>{{r.filled_at|date:'medium'}}</td><td><code>{{shortId(r.order_id)}}</code></td><td><strong>{{r.symbol}}</strong></td><td><span class="side-badge" [class.sell]="r.side==='SELL'">{{r.side}}</span></td><td class="numeric">{{r.quantity|number:'1.0-8'}}</td><td class="numeric">{{r.notional|number:'1.2-2'}} {{r.currency}}</td></tr>}@empty{<tr><td colspan="7" class="empty">No warehouse rows available.</td></tr>}</tbody></table></section>`})
export class WarehouseActivityComponent{
 private api=inject(ApiService);summary=signal<ReportSummary|null>(null);recent=signal<TradeActivity[]>([]);loadsByDay=signal<ChartDatum[]>([]);tradesBySymbol=signal<ChartDatum[]>([]);
 constructor(){this.load();}
 load(){this.api.reportSummary().subscribe(x=>this.summary.set(x));this.api.reportActivity().subscribe(rows=>{const sorted=[...rows].sort((a,b)=>Date.parse(b.loaded_at)-Date.parse(a.loaded_at));this.recent.set(sorted.slice(0,20));const days=new Map<string,number>(),symbols=new Map<string,number>();for(const r of rows){const day=new Date(r.loaded_at).toLocaleDateString(undefined,{month:'short',day:'numeric'});days.set(day,(days.get(day)??0)+1);symbols.set(r.symbol,(symbols.get(r.symbol)??0)+1);}this.loadsByDay.set([...days].map(([label,value])=>({label,value})));this.tradesBySymbol.set([...symbols].sort((a,b)=>b[1]-a[1]).map(([label,value])=>({label,value})));});}
 shortId(id:string){return 'ORD-'+id.replaceAll('-','').slice(0,8).toUpperCase();}
}
