import { Component,inject,signal } from '@angular/core';import { Router } from '@angular/router';import { AuthService } from './auth.service';
/** Header controls showing access-token time remaining and explicit logout. */
@Component({selector:'app-session-header',standalone:true,styles:[`:host{display:block;color:inherit}.session-header{display:flex;align-items:center;gap:12px;font-size:12px;white-space:nowrap;color:inherit}.session-timer{display:flex;align-items:baseline;gap:7px;padding:7px 10px;border:1px solid #cbd5e1;border-radius:7px;background:#f8fafc;color:#172033;font-variant-numeric:tabular-nums;opacity:1!important;transition:background .2s,border-color .2s,color .2s}.session-timer small{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:#667085!important;font-weight:700;opacity:1!important}.session-timer strong{font-size:16px;letter-spacing:.025em;color:#172033!important;line-height:1;opacity:1!important}.session-timer.expiring{background:#7f1d1d!important;border-color:#ef4444!important;color:#fff!important;box-shadow:0 0 0 1px rgba(239,68,68,.16)}.session-timer.expiring small,.session-timer.expiring strong{color:#fff!important}.session-header button{padding:6px 10px;border:1px solid #94a3b8;border-radius:4px;background:transparent;color:inherit;cursor:pointer}.session-header button:hover{background:rgba(127,127,127,.12)}`],template:`@if(auth.isAuthenticated()){<div class="session-header"><span class="session-timer" [class.expiring]="expiring()" title="Access token time remaining"><small>Session</small><strong>{{remaining()}}</strong></span><button type="button" (click)="logout()">Logout</button></div>}`})
export class SessionHeaderComponent{
 readonly auth=inject(AuthService);private router=inject(Router);readonly remaining=signal('--:--');readonly expiring=signal(false);private tick?:number;
 constructor(){this.update();this.tick=window.setInterval(()=>this.update(),1000);window.addEventListener('auth-session-changed',()=>this.update());}
 private update(){const exp=this.auth.expiresAt();if(!exp){this.remaining.set('--:--');this.expiring.set(false);return;}const s=Math.max(0,Math.ceil((exp-Date.now())/1000));this.expiring.set(s<=300);this.remaining.set(`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`);}
 logout(){this.auth.logout();this.router.navigate(['/login']);}
}
