import { Component,input } from '@angular/core';import { DecimalPipe } from '@angular/common';
export interface ChartDatum{label:string;value:number}
@Component({selector:'app-simple-chart',standalone:true,imports:[DecimalPipe],styles:[`
:host{display:block}.chart-card{background:#fff;border:1px solid #dfe5ec;border-radius:8px;padding:18px 20px;box-shadow:0 4px 14px rgba(21,34,56,.06);height:100%}.chart-card h3{margin:0;font-size:16px}.chart-card>p{margin:4px 0 18px;color:#667085;font-size:12px}.bars{display:grid;gap:11px}.bar-row{display:grid;grid-template-columns:72px minmax(0,1fr) 92px;gap:10px;align-items:center;font-size:12px}.bar-label{font-weight:700;overflow:hidden;text-overflow:ellipsis}.track{height:10px;background:#edf1f5;border-radius:8px;overflow:hidden}.fill{height:100%;background:#2b61ad;border-radius:8px;min-width:2px}.fill.negative{background:#b42318}.bar-value{text-align:right;font-variant-numeric:tabular-nums;font-weight:650}.donut-wrap{display:grid;grid-template-columns:160px 1fr;gap:20px;align-items:center}.donut{width:150px;height:150px;border-radius:50%;position:relative;margin:auto}.donut:after{content:"";position:absolute;inset:32px;border-radius:50%;background:#fff}.legend{display:grid;gap:9px}.legend-row{display:grid;grid-template-columns:12px 1fr auto;gap:8px;align-items:center;font-size:12px}.dot{width:9px;height:9px;border-radius:50%;background:var(--dot)}.legend-row strong{font-variant-numeric:tabular-nums}@media(max-width:600px){.donut-wrap{grid-template-columns:1fr}.bar-row{grid-template-columns:58px minmax(0,1fr) 78px}}`],template:`
<section class="chart-card"><h3>{{title()}}</h3><p>{{subtitle()}}</p>
@if(type()==='donut'){<div class="donut-wrap"><div class="donut" [style.background]="gradient()"></div><div class="legend">@for(d of data();track d.label;let i=$index){<div class="legend-row"><span class="dot" [style.--dot]="colors[i%colors.length]"></span><span>{{d.label}}</span><strong>{{d.value|number:'1.0-2'}}</strong></div>}</div></div>}
@else{<div class="bars">@for(d of data();track d.label){<div class="bar-row"><span class="bar-label">{{d.label}}</span><div class="track"><div class="fill" [class.negative]="d.value<0" [style.width.%]="barWidth(d.value)"></div></div><span class="bar-value">{{prefix()}}{{d.value|number:'1.0-2'}}</span></div>}</div>}
</section>`})
export class SimpleChartComponent{
 title=input.required<string>();subtitle=input('');type=input<'bar'|'donut'>('bar');data=input<ChartDatum[]>([]);prefix=input('');
 readonly colors=['#2b61ad','#16a085','#7c5ce5','#d97706','#4f7f52','#be4b72','#64748b'];
 max(){return Math.max(1,...this.data().map(x=>Math.abs(x.value)));}
 barWidth(v:number){return Math.max(2,Math.abs(v)/this.max()*100);}
 gradient(){const rows=this.data().filter(x=>x.value>0),total=rows.reduce((s,x)=>s+x.value,0);if(!total)return '#edf1f5';let at=0;const stops=rows.map((x,i)=>{const start=at;at+=x.value/total*100;return `${this.colors[i%this.colors.length]} ${start}% ${at}%`;});return `conic-gradient(${stops.join(',')})`;}
}
